NETWORK_BOSS_INIT_VALUE = 15000
RAND_THRESHOLD_DIRECT_TRANSACTION = 0.25
TIME_WAIT_LOW_BOUND = 0.05 #secunde. (0.05)
TIME_WAIT_HI_BOUND = 0.7 #secunde. (0.7)
NETWORK_NODE_COUNT = 15 #fara seful retelei.